// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYIrL_4-SXD3-89WdKjBH0XGRs3MJFVSY',
    appId: '1:451664357800:web:a07e29592e3d0cfb1d559d',
    messagingSenderId: '451664357800',
    projectId: 'webo-database',
    authDomain: 'webo-database.firebaseapp.com',
    storageBucket: 'webo-database.firebasestorage.app',
    measurementId: 'G-YG7Q2B41QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoxW82_KNzVGjkGUUwa_KnQTd4rzM9c5A',
    appId: '1:451664357800:android:fcbdc75a970040a51d559d',
    messagingSenderId: '451664357800',
    projectId: 'webo-database',
    storageBucket: 'webo-database.firebasestorage.app',
  );
}
